LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

APP_CPPFLAGS += -frtti -fexceptions -fpermissive -gstabs+

LOCAL_MODULE := game_logic_static
LOCAL_MODULE_FILENAME := libgame_logic

LOCAL_C_FLAGS += -fuse-ld=gold
LOCAL_C_FLAGS += -fpermissive
LOCAL_CPP_FLAGS += -fuse-ld=gold 
LOCAL_CPP_FLAGS += -fpermissive

LOCAL_LDLIBS := -gstabs+ -lcocosdenshion -llog

LOCAL_SRC_FILES := \
	Game/model/tower/TowerProxy.cpp \
	Game/model/task/vo/EntrTaskVo.cpp \
	Game/model/task/vo/TaskVo.cpp \
	Game/model/task/vo/TaskTipVo.cpp \
	Game/model/task/AutoTaskManager.cpp \
	Game/model/task/TaskManager.cpp \
	Game/model/task/TaskProxy.cpp \
	Game/model/player/vo/AccountInfoVo.cpp \
	Game/model/player/PlayerEffectManage.cpp \
	Game/model/player/RoleManage.cpp \
	Game/model/player/FigureBaseManage.cpp \
	Game/model/player/ClothManage.cpp \
	Game/model/zx/XHConfManager.cpp \
	Game/model/appoint/AppointManager.cpp \
	Game/model/bank/BankProxy.cpp \
	Game/model/shop/ShopManager.cpp \
	Game/model/shop/ShopManage.cpp \
	Game/model/shop/ItemRiseInfo.cpp \
	Game/model/figure/vo/EquipSkillVo.cpp \
	Game/model/figure/vo/EquipmentVo.cpp \
	Game/model/figure/LevelExpManage.cpp \
	Game/model/figure/FigureProxy.cpp \
	Game/model/figure/EquipmentManager.cpp \
	Game/model/arena/ArenaProxy.cpp \
	Game/model/arena/ArenaConst.cpp \
	Game/model/arena/ArenaManage.cpp \
	Game/model/dungeonEntrys/DungeonEntrysManage.cpp \
	Game/model/notice/NoticeManager.cpp \
	Game/model/notice/NoticeType.cpp \
	Game/model/notice/NoticeProxy.cpp \
	Game/model/formation/FormationProxy.cpp \
	Game/model/formation/vo/FormationInfo.cpp \
	Game/model/formation/vo/NodeObject.cpp \
	Game/model/vip/VipProxy.cpp \
	Game/model/vip/VipManager.cpp \
	Game/model/battle/FightProxy.cpp \
	Game/model/battle/BattleProxy.cpp \
	Game/model/recruit/vo/RecruitInfo.cpp \
	Game/model/recruit/RecruitProxy.cpp \
	Game/model/dailyTaskEx/DailyTaskExProxy.cpp \
	Game/model/train/vo/TrainManager.cpp \
	Game/model/train/TrainProxy.cpp \
	Game/model/newhand/vo/StepVo.cpp \
	Game/model/newhand/vo/ScriptVo.cpp \
	Game/model/newhand/vo/HelpScriptVo.cpp \
	Game/model/newhand/NewhandManager.cpp \
	Game/model/streng/StrengManage.cpp \
	Game/model/honor/vo/HonorManage.cpp \
	Game/model/honor/vo/HonorScheduleManage.cpp \
	Game/model/honor/HonorProxy.cpp \
	Game/model/onlineReward/OnlineRewardManager.cpp \
	Game/model/onlineReward/OnlineRewardProxy.cpp \
	Game/model/guild/GuildManager.cpp \
	Game/model/skill/SkillTipsTool.cpp \
	Game/model/skill/SkillProxy.cpp \
	Game/model/skill/SkillManager.cpp \
	Game/model/magic/MagicManage.cpp \
	Game/model/backpack/GoodsManager.cpp \
	Game/model/backpack/BagProxy.cpp \
	Game/model/silverMine/SilverMineManage.cpp \
	Game/model/silverMine/SilverMineProxy.cpp \
	Game/model/trader/TraderProxy.cpp \
	Game/model/trader/TraderManager.cpp \
	Game/model/campFight/CampFightProxy.cpp \
	Game/model/config/ConfigManager.cpp \
	Game/model/dialog/DialogManager.cpp \
	Game/model/worldBoss/WorldBossProxy.cpp \
	Game/model/friend/FriendProxy.cpp \
	Game/model/scene/queue/PlayerQueueManager.cpp \
	Game/model/scene/vo/SceneInfoVo.cpp \
	Game/model/scene/fight/vo/BattleData.cpp \
	Game/model/scene/fight/sweeper/DropoutStory.cpp \
	Game/model/scene/fight/sweeper/PassbyStory.cpp \
	Game/model/scene/fight/CombatDataManage.cpp \
	Game/model/scene/MonsterManager.cpp \
	Game/model/scene/StoryProxy.cpp \
	Game/model/scene/StoryManager.cpp \
	Game/model/scene/SceneProxy.cpp \
	Game/model/scene/NPCManager.cpp \
	Game/model/scene/FuncExitManager.cpp \
	Game/model/scene/SentenceManager.cpp \
	Game/model/scene/TokenManager.cpp \
	Game/model/scene/PathPointManager.cpp \
	Game/model/scene/SceneManager.cpp \
	Game/model/scene/ExitManager.cpp \
	Game/model/mail/MailProxy.cpp \
	Game/model/crystal/vo/CrystalType.cpp \
	Game/model/crystal/vo/UpgradePreTip.cpp \
	Game/model/crystal/vo/CrystalInfo.cpp \
	Game/model/crystal/CrystalManager.cpp \
	Game/model/crystal/CrystalProxy.cpp \
	Game/model/chat/ChannelType.cpp \
	Game/model/ranking/RankingProxy.cpp \
	Game/model/com/GoodsDynamicManager.cpp \
	Game/model/com/GoodsToolTips.cpp \
	Game/model/com/ResourceManage.cpp \
	Game/model/egg/EggManager.cpp \
	Game/model/egg/EggProxy.cpp \
	Game/manager/sound/ActionPlayer.cpp \
	Game/manager/sound/SoundManager.cpp \
	Game/manager/BattleManager.cpp \
	Game/manager/SourceCacheManage.cpp \
	Game/manager/layer/LoadingLayer.cpp \
	Game/manager/layer/ArenaUILayer.cpp \
	Game/manager/layer/TipsLayer.cpp \
	Game/manager/layer/SilverMineLayer.cpp \
	Game/manager/layer/SceneUILayer.cpp \
	Game/manager/layer/WorldLayer.cpp \
	Game/manager/layer/PreTipsLayer.cpp \
	Game/manager/layer/WindowLayer.cpp \
	Game/manager/layer/IntervalLayer.cpp \
	Game/manager/layer/MapManage.cpp \
	Game/manager/PopManage.cpp \
	Game/manager/OverPanelManage.cpp \
	Game/manager/CDManage.cpp \
	Game/manager/ImageManager.cpp \
	Game/manager/RenderManage.cpp \
	Game/manager/ConnectionManager.cpp \
	Game/manager/VIPMgr.cpp \
	Game/manager/UILayerManager.cpp \
	Game/manager/ViewManager.cpp \
	Game/manager/SystemManage.cpp \
	Game/manager/NameManager.cpp \
	Game/manager/GlobalManage.cpp \
	Game/manager/LayerManager.cpp \
	Game/manager/TimerManage.cpp \
	Game/utils/Utils.cpp \
	Game/utils/TipsXHCanvas.cpp \
	Game/utils/TipsSkillCanvas.cpp \
	Game/utils/effect/FightEffectGroup.cpp \
	Game/utils/effect/Effect1.cpp \
	Game/utils/effect/FightEffect.cpp \
	Game/utils/effect/TweenLiteObject.cpp \
	Game/utils/EffectHelps.cpp \
	Game/utils/TipsEquipCanvas.cpp \
	Game/utils/ValuesUtil.cpp \
	Game/utils/TipHelps.cpp \
	Game/utils/TipBase.cpp \
	Game/utils/BitmapMovieClip.cpp \
	Game/view/tower/components/TowerRankItem.cpp \
	Game/view/tower/components/TowerConfirm.cpp \
	Game/view/tower/components/FightPanel.cpp \
	Game/view/tower/components/TowerRank.cpp \
	Game/view/tower/components/TowerPageNav.cpp \
	Game/view/tower/components/TowerView.cpp \
	Game/view/tower/components/EnterPanel.cpp \
	Game/view/tower/components/ListContainer.cpp \
	Game/view/tower/TowerMediator.cpp \
	Game/view/load/LoadStorySceneMediator.cpp \
	Game/view/task/TaskListenerMediator.cpp \
	Game/view/task/TaskFollowMediator.cpp \
	Game/view/task/components/TaskView.cpp \
	Game/view/task/components/TaskUIView.cpp \
	Game/view/task/components/TaskItem.cpp \
	Game/view/task/components/UITaskFollowListContentLayer.cpp \
	Game/view/task/components/TaskScrollView.cpp \
	Game/view/task/components/TaskFollowView.cpp \
	Game/view/task/components/TaskStrConcat.cpp \
	Game/view/task/components/TaskAutoFindNpc.cpp \
	Game/view/task/components/TaskCatType.cpp \
	Game/view/task/TaskMediator.cpp \
	Game/view/fight/callback/ArenaCallbackAction.cpp \
	Game/view/fight/callback/ShowAttrChangeAction.cpp \
	Game/view/fight/callback/UpdatePraceticeAction.cpp \
	Game/view/fight/callback/SpecialItemAddAction.cpp \
	Game/view/fight/callback/UpdatePopularityAction.cpp \
	Game/view/fight/callback/ShowNotificationAction.cpp \
	Game/view/fight/callback/FightFollowWorldBossAction.cpp \
	Game/view/fight/callback/FightFollowStoryAction.cpp \
	Game/view/fight/callback/FightFollowLevelUpAction.cpp \
	Game/view/fight/callback/ShowNewHandHelpAction.cpp \
	Game/view/fight/callback/fightCallBackTipsAction.cpp \
	Game/view/fight/callback/UpdateSilverAction.cpp \
	Game/view/fight/callback/CDEnergyAction.cpp \
	Game/view/GameView.cpp \
	Game/view/zx/components/XHFigure.cpp \
	Game/view/zx/components/ZXCollectXH.cpp \
	Game/view/zx/components/ZXer.cpp \
	Game/view/zx/components/XHCopy.cpp \
	Game/view/zx/components/ZXView.cpp \
	Game/view/zx/components/ZXDuiView.cpp \
	Game/view/zx/components/XH.cpp \
	Game/view/zx/components/XHView.cpp \
	Game/view/zx/ZXMediator.cpp \
	Game/view/appoint/components/AppointBlessView.cpp \
	Game/view/appoint/components/GoodsView.cpp \
	Game/view/appoint/components/AppointView.cpp \
	Game/view/appoint/AppointMediator.cpp \
	Game/view/bank/components/BankView.cpp \
	Game/view/bank/components/BankItemInfoShow.cpp \
	Game/view/bank/components/BankGoods.cpp \
	Game/view/bank/components/BankUIPartialScrollView.cpp \
	Game/view/bank/components/BankCreate.cpp \
	Game/view/bank/BankMediator.cpp \
	Game/view/shop/components/ShopCreate.cpp \
	Game/view/shop/components/ShopUIPartialScrollView.cpp \
	Game/view/shop/components/ShopGoods.cpp \
	Game/view/shop/components/ShopView.cpp \
	Game/view/shop/ShopMediator.cpp \
	Game/view/figure/components/SkillItem.cpp \
	Game/view/figure/components/IdentifyView.cpp \
	Game/view/figure/components/AttributeLayer.cpp \
	Game/view/figure/components/SkillUIPartialScrollView.cpp \
	Game/view/figure/components/PeiyangView.cpp \
	Game/view/figure/components/SkillCells.cpp \
	Game/view/figure/components/SkillLayer.cpp \
	Game/view/figure/components/FigureCreate.cpp \
	Game/view/figure/components/FigureView.cpp \
	Game/view/figure/components/NameUIPartialScrollView.cpp \
	Game/view/figure/components/EquiptmentItem.cpp \
	Game/view/figure/components/FigureMainUI.cpp \
	Game/view/figure/components/FigureMainView.cpp \
	Game/view/figure/components/SkillView.cpp \
	Game/view/figure/components/StuntsLayer.cpp \
	Game/view/figure/FigureMediator.cpp \
	Game/view/login/components/AreaListView.cpp \
	Game/view/login/components/LoginTxtItem.cpp \
	Game/view/login/components/LoginNewMain.cpp \
	Game/view/login/components/LoginServer.cpp \
	Game/view/login/components/ServerNewListView.cpp \
	Game/view/login/components/LoginCreateRole.cpp \
	Game/view/login/components/LoginMain.cpp \
	Game/view/login/components/LoginTxt.cpp \
	Game/view/login/components/LoginRegister.cpp \
	Game/view/login/components/ServerListView.cpp \
	Game/view/login/components/LoginView.cpp \
	Game/view/login/LoginMediator.cpp \
	Game/view/GameViewMediator.cpp \
	Game/view/levy/components/LevyView.cpp \
	Game/view/levy/components/GoldLevyPanel.cpp \
	Game/view/levy/LevyMediator.cpp \
	Game/view/arena/ArenaMediator.cpp \
	Game/view/arena/components/RankList.cpp \
	Game/view/arena/components/GiftPanel.cpp \
	Game/view/arena/components/ReportList.cpp \
	Game/view/arena/components/InfoPanel.cpp \
	Game/view/arena/components/HeroRankItem.cpp \
	Game/view/arena/components/CardList.cpp \
	Game/view/arena/components/RankingInfo.cpp \
	Game/view/arena/components/HeroRankView.cpp \
	Game/view/arena/components/ArenaUI.cpp \
	Game/view/arena/components/StarRecord.cpp \
	Game/view/arena/components/RankItem.cpp \
	Game/view/dungeonEntrys/components/DungeonGuaView.cpp \
	Game/view/dungeonEntrys/components/DungeonEntrysView.cpp \
	Game/view/dungeonEntrys/components/ChallengeMapsView.cpp \
	Game/view/dungeonEntrys/components/ChallengeMapLists.cpp \
	Game/view/dungeonEntrys/components/DungeonGUAMonsterInfoItem.cpp \
	Game/view/dungeonEntrys/components/StoryCityLists.cpp \
	Game/view/dungeonEntrys/components/TouchMapNode.cpp \
	Game/view/dungeonEntrys/components/TouchCityNode.cpp \
	Game/view/dungeonEntrys/components/DungeonGUAMonsterInfoLayer.cpp \
	Game/view/dungeonEntrys/components/StoryMapLists.cpp \
	Game/view/dungeonEntrys/components/DungeonEntrysCreate.cpp \
	Game/view/dungeonEntrys/components/DungeonGUAMsgItem.cpp \
	Game/view/dungeonEntrys/components/ChallengeGuaView.cpp \
	Game/view/dungeonEntrys/components/StoryMapsView.cpp \
	Game/view/dungeonEntrys/DungeonEntrysMediator.cpp \
	Game/view/formation/FormationMediator.cpp \
	Game/view/formation/components/FormationSprite.cpp \
	Game/view/formation/components/FormationItem.cpp \
	Game/view/formation/components/HeadItem.cpp \
	Game/view/formation/components/FormationView.cpp \
	Game/view/formation/components/FormationClip.cpp \
	Game/view/gong/components/GongRankingView.cpp \
	Game/view/gong/components/GongMBView.cpp \
	Game/view/gong/GongMediator.cpp \
	Game/view/vip/VipMediator.cpp \
	Game/view/vip/components/VipGiftView.cpp \
	Game/view/vip/components/VipScrollView.cpp \
	Game/view/vip/components/VipView.cpp \
	Game/view/battle/SceneFightMediator.cpp \
	Game/view/recruit/RecruitMediator.cpp \
	Game/view/recruit/components/SkillPic.cpp \
	Game/view/recruit/components/RecruitView.cpp \
	Game/view/recruit/components/RecruitPanel.cpp \
	Game/view/recruit/components/RecruitTips.cpp \
	Game/view/recruit/components/RecruitItem.cpp \
	Game/view/mainUI/PlayerMediator.cpp \
	Game/view/mainUI/components/MainNavigate.cpp \
	Game/view/mainUI/components/RoleUI.cpp \
	Game/view/mainUI/components/VScrollUI.cpp \
	Game/view/mainUI/components/MainNavigateX.cpp \
	Game/view/mainUI/components/SecNavigate.cpp \
	Game/view/mainUI/components/VSCustomCD.cpp \
	Game/view/mainUI/components/MainNavigateY.cpp \
	Game/view/mainUI/MainUIMediator.cpp \
	Game/view/report/components/MapAwardPanel.cpp \
	Game/view/report/components/ReportView.cpp \
	Game/view/report/components/PassGiftSkin.cpp \
	Game/view/report/ReportMediator.cpp \
	Game/view/setting/components/SoundSetLayer.cpp \
	Game/view/setting/components/MainSettingLayer.cpp \
	Game/view/setting/components/SettingView.cpp \
	Game/view/setting/components/AccountSettingLayer.cpp \
	Game/view/guest/RegisterMediator.cpp \
	Game/view/guest/components/GuestRegisterView.cpp \
	Game/view/guest/components/RegisterBtnView.cpp \
	Game/view/guest/GuestMediator.cpp \
	Game/view/dailyTaskEx/DailyTaskExMediator.cpp \
	Game/view/dailyTaskEx/components/DailyTaskExView.cpp \
	Game/view/train/TrainViewMediator.cpp \
	Game/view/train/components/TrainTime.cpp \
	Game/view/train/components/TrainView.cpp \
	Game/view/train/components/RoleListView.cpp \
	Game/view/train/components/TrainRoleItem.cpp \
	Game/view/newhand/NewhandMediator.cpp \
	Game/view/newhand/components/NewHandView.cpp \
	Game/view/newhand/components/LeaderAlert.cpp \
	Game/view/newhand/components/LeadArrow.cpp \
	Game/view/newhand/components/ObjectGlow.cpp \
	Game/view/newhand/components/NewHandHelpView.cpp \
	Game/view/map/MapMediator.cpp \
	Game/view/map/components/NoiseSnow.cpp \
	Game/view/map/components/Map.cpp \
	Game/view/map/components/SmallMapElement.cpp \
	Game/view/map/components/MapElement.cpp \
	Game/view/map/components/NPCItem.cpp \
	Game/view/honor/HonorMediator.cpp \
	Game/view/onlineReward/RewardMediator.cpp \
	Game/view/onlineReward/components/RewardItem.cpp \
	Game/view/onlineReward/components/OnlineRewardView.cpp \
	Game/view/onlineReward/components/RewardListView.cpp \
	Game/view/guild/GuildListenerMediator.cpp \
	Game/view/guild/GuildMediator.cpp \
	Game/view/guild/components/VerifyItem.cpp \
	Game/view/guild/components/ListMenu.cpp \
	Game/view/guild/components/CreateGuild.cpp \
	Game/view/guild/components/GuildView.cpp \
	Game/view/guild/components/PageNav.cpp \
	Game/view/guild/components/MemberPanel.cpp \
	Game/view/guild/components/GuildView_init.cpp \
	Game/view/guild/components/TechPanel.cpp \
	Game/view/guild/components/GuildTabPanel.cpp \
	Game/view/guild/components/GuildEditView.cpp \
	Game/view/guild/components/GuildDispatcher.cpp \
	Game/view/guild/components/MemberItem.cpp \
	Game/view/guild/components/VerifyPanel.cpp \
	Game/view/guild/components/GuildPreView.cpp \
	Game/view/guild/components/CommonList.cpp \
	Game/view/guild/components/GuildInfoView.cpp \
	Game/view/guild/components/GuildItem.cpp \
	Game/view/guild/components/DonateView.cpp \
	Game/view/skill/components/UpSkillView.cpp \
	Game/view/skill/components/UPSkillCreate.cpp \
	Game/view/skill/components/UPSkillItem.cpp \
	Game/view/skill/components/UPSkillPopUIBg.cpp \
	Game/view/skill/UpSkillMediator.cpp \
	Game/view/backpack/BagMediator.cpp \
	Game/view/backpack/components/BagGoods.cpp \
	Game/view/backpack/components/BagUIPartialScrollView.cpp \
	Game/view/backpack/components/ItemInfoShow.cpp \
	Game/view/backpack/components/BagCreate.cpp \
	Game/view/backpack/components/BagView.cpp \
	Game/view/broadcast/BroadcastMediator.cpp \
	Game/view/broadcast/components/NoticeBanner.cpp \
	Game/view/silverMine/SilverMineMediator.cpp \
	Game/view/silverMine/component/MineOpt.cpp \
	Game/view/silverMine/component/MineBg.cpp \
	Game/view/silverMine/component/MineTips.cpp \
	Game/view/silverMine/component/MineView.cpp \
	Game/view/silverMine/component/MinePanel.cpp \
	Game/view/silverMine/component/MineInfo.cpp \
	Game/view/silverMine/component/MineItem.cpp \
	Game/view/silverMine/component/MineRank.cpp \
	Game/view/trader/components/TraderView.cpp \
	Game/view/trader/components/MyRobPanel.cpp \
	Game/view/trader/components/TraderGoodsItem.cpp \
	Game/view/trader/components/RobPanel.cpp \
	Game/view/trader/CityTraderMediator.cpp \
	Game/view/campFight/components/CampFightPlayerListView.cpp \
	Game/view/campFight/components/CampFightMsgListViewItem.cpp \
	Game/view/campFight/components/CampFightView.cpp \
	Game/view/campFight/components/MsgItem.cpp \
	Game/view/campFight/CampFightMediator.cpp \
	Game/view/loading/LoadingView.cpp \
	Game/view/dialog/DialogMediator.cpp \
	Game/view/dialog/components/DialogView.cpp \
	Game/view/dialog/components/DialogUtil.cpp \
	Game/view/smallMap/components/SmallMap.cpp \
	Game/view/smallMap/components/SmallMapUI.cpp \
	Game/view/smallMap/components/SmallElement.cpp \
	Game/view/smallMap/SmallMapMediator.cpp \
	Game/view/worldBoss/WorldBossMediator.cpp \
	Game/view/worldBoss/components/DeathView.cpp \
	Game/view/worldBoss/components/WorldBossMainView.cpp \
	Game/view/worldBoss/components/BossHPView.cpp \
	Game/view/worldBoss/components/QuitView.cpp \
	Game/view/worldBoss/components/BoostView.cpp \
	Game/view/worldBoss/components/DamageRankView.cpp \
	Game/view/friend/FriendMediator.cpp \
	Game/view/friend/FriendListenerMediator.cpp \
	Game/view/friend/components/FItemCheck.cpp \
	Game/view/friend/components/FListItem.cpp \
	Game/view/friend/components/FriendView.cpp \
	Game/view/friend/components/FriendUIPartialScrollView.cpp \
	Game/view/friend/components/FPContainer.cpp \
	Game/view/scene/layer/FightLayer.cpp \
	Game/view/scene/layer/BattleLayer.cpp \
	Game/view/scene/SceneMediator.cpp \
	Game/view/scene/SceneWorldMediator.cpp \
	Game/view/scene/SceneListenerMediator.cpp \
	Game/view/scene/SceneStoryMediator.cpp \
	Game/view/scene/components/EndBtnTips.cpp \
	Game/view/scene/components/story/callback/StoryFollowNoticeAction.cpp \
	Game/view/scene/components/story/callback/StoryFollowTipsAction.cpp \
	Game/view/scene/components/story/callback/StoryFollowNotifyAction.cpp \
	Game/view/scene/components/story/FocusManage.cpp \
	Game/view/scene/components/story/StoryEffect.cpp \
	Game/view/scene/components/story/StoryEffectManage.cpp \
	Game/view/scene/components/story/VirtualFocus.cpp \
	Game/view/scene/components/LiveThing.cpp \
	Game/view/scene/components/fight/ActionHandler.cpp \
	Game/view/scene/components/fight/FormationLoader.cpp \
	Game/view/scene/components/fight/BattleEnginer.cpp \
	Game/view/scene/components/fight/BuffsHandler.cpp \
	Game/view/scene/components/fight/FightEnd.cpp \
	Game/view/scene/components/ChildExitContainer.cpp \
	Game/view/scene/components/FightSpecialFontField.cpp \
	Game/view/scene/components/ImageTxt.cpp \
	Game/view/scene/components/Exit.cpp \
	Game/view/scene/components/LoginScene.cpp \
	Game/view/scene/components/BattlePlay.cpp \
	Game/view/scene/components/MainScene.cpp \
	Game/view/scene/components/MapNPCSprite.cpp \
	Game/view/scene/components/FightSkillTextField.cpp \
	Game/view/scene/components/BaseLayer.cpp \
	Game/view/scene/components/Element.cpp \
	Game/view/scene/components/BaseScene.cpp \
	Game/view/scene/components/Scene.cpp \
	Game/view/scene/components/ChildExit.cpp \
	Game/view/scene/components/BgBitmap.cpp \
	Game/view/scene/components/FightScene.cpp \
	Game/view/scene/components/DungeonView.cpp \
	Game/view/scene/components/MapNPC.cpp \
	Game/view/scene/components/StoryScene.cpp \
	Game/view/scene/components/WorldExit.cpp \
	Game/view/scene/components/DungeonAwardAction.cpp \
	Game/view/scene/components/FightAoyiTextField.cpp \
	Game/view/scene/components/WorldBgBitmap.cpp \
	Game/view/scene/components/chat/WhisperContainer.cpp \
	Game/view/scene/components/chat/LeftChatContainer.cpp \
	Game/view/scene/components/chat/StoryChatUIPrintView.cpp \
	Game/view/scene/components/chat/ChatContainer.cpp \
	Game/view/scene/components/chat/RightChatContainer.cpp \
	Game/view/scene/components/WorldScene.cpp \
	Game/view/scene/components/Item.cpp \
	Game/view/scene/components/NPCChat.cpp \
	Game/view/scene/components/Npc.cpp \
	Game/view/scene/components/Player.cpp \
	Game/view/mail/MailMediator.cpp \
	Game/view/mail/components/MailView.cpp \
	Game/view/mail/components/MailScrollView.cpp \
	Game/view/mail/components/MailAttachItem.cpp \
	Game/view/mail/components/MailItem.cpp \
	Game/view/ore/OreMediator.cpp \
	Game/view/ore/components/OreHelpView.cpp \
	Game/view/ore/components/OreItem.cpp \
	Game/view/ore/components/OreView.cpp \
	Game/view/ore/components/PlantView.cpp \
	Game/view/ore/components/PlantItem.cpp \
	Game/view/ce/components/ceView.cpp \
	Game/view/crystal/components/CrystalCDList.cpp \
	Game/view/crystal/components/CrystalTimer.cpp \
	Game/view/crystal/components/CrystalUIPartialScrollView.cpp \
	Game/view/crystal/components/CrystalView.cpp \
	Game/view/crystal/CrystalMediator.cpp \
	Game/view/mainStreng/components/StrengGoods.cpp \
	Game/view/mainStreng/components/StrengFigureCreate.cpp \
	Game/view/mainStreng/components/StrengPanel.cpp \
	Game/view/mainStreng/components/StrengCreate.cpp \
	Game/view/mainStreng/components/MeltingBagGoods.cpp \
	Game/view/mainStreng/components/MeltingStrengCreate.cpp \
	Game/view/mainStreng/components/StrengCreateBagListView.cpp \
	Game/view/mainStreng/components/MeltingPanel.cpp \
	Game/view/mainStreng/components/HeritagePanel.cpp \
	Game/view/mainStreng/components/HeritageGoods.cpp \
	Game/view/mainStreng/components/MeltingTips.cpp \
	Game/view/mainStreng/components/MagicPanel.cpp \
	Game/view/mainStreng/components/HeritageCreate.cpp \
	Game/view/mainStreng/components/FigureItem.cpp \
	Game/view/mainStreng/components/MeltingUIListView.cpp \
	Game/view/mainStreng/components/MainStrengView.cpp \
	Game/view/mainStreng/components/MeltingBagCreate.cpp \
	Game/view/mainStreng/MainStrengMediator.cpp \
	Game/view/chat/ChatMediator.cpp \
	Game/view/chat/components/FindPMLayer.cpp \
	Game/view/chat/components/ChatView.cpp \
	Game/view/chat/components/ChatPopContainer.cpp \
	Game/view/chat/components/ChatTextPanel.cpp \
	Game/view/chat/components/ChatMsgManager.cpp \
	Game/view/chat/components/ChatItem.cpp \
	Game/view/chat/components/SceneChatItem.cpp \
	Game/view/chat/components/ChatBtnMenu.cpp \
	Game/view/chat/components/ChannelBtnClickLayer.cpp \
	Game/view/ranking/RankingMediator.cpp \
	Game/view/ranking/components/RankingListView.cpp \
	Game/view/ranking/components/RenownPanel.cpp \
	Game/view/ranking/components/CapacityPanel.cpp \
	Game/view/ranking/components/RankEqItem.cpp \
	Game/view/ranking/components/RankingView.cpp \
	Game/view/ranking/components/FigureItemView.cpp \
	Game/view/purchase/PurchaseMediator.cpp \
	Game/view/purchase/components/FirstPurchaseView.cpp \
	Game/view/purchase/components/PurchaseView.cpp \
	Game/view/noticeCenter/components/NoticeItem.cpp \
	Game/view/noticeCenter/components/suit/MineBtn.cpp \
	Game/view/noticeCenter/components/CenterView.cpp \
	Game/view/noticeCenter/MsgMediator.cpp \
	Game/view/notify/NotifyLayer.cpp \
	Game/view/notify/NotifyManager.cpp \
	Game/view/notify/NotifyGrid.cpp \
	Game/view/egg/components/RewardPanel.cpp \
	Game/view/egg/components/WashPanel.cpp \
	Game/view/egg/components/GoodsItem.cpp \
	Game/view/egg/components/PoolViewInit.cpp \
	Game/view/egg/components/ReserveDepot.cpp \
	Game/view/egg/components/NumSelectBox.cpp \
	Game/view/egg/components/ShowItem.cpp \
	Game/view/egg/components/PoolView.cpp \
	Game/view/egg/EggMediator.cpp \
	Game/view/act/ActMediator.cpp \
	Game/view/act/components/HotList.cpp \
	Game/view/act/components/ActView.cpp \
	Game/view/act/components/ActItem.cpp \
	Game/view/equipmentDrop/components/DropCheckView.cpp \
	Game/view/equipmentDrop/components/EqItem.cpp \
	Game/view/equipmentDrop/components/EqCreate.cpp \
	Game/view/equipmentDrop/components/CustomComboBox.cpp \
	Game/view/equipmentDrop/DropMediator.cpp \
	Game/util/TileUtil.cpp \
	Game/socket/network/GameServerSocket.cpp \
	Game/socket/network/cocos_socket.cpp \
	Game/socket/network/GateServerSocket.cpp \
	Game/socket/network/PacketBuffer.cpp \
	Game/socket/network/Packet.cpp \
	Game/socket/message/MessageFactoryManager.cpp \
	Game/socket/command/c46/CCMD461.cpp \
	Game/socket/command/c46/CCMD466.cpp \
	Game/socket/command/c46/CCMD469.cpp \
	Game/socket/command/c46/CCMD467.cpp \
	Game/socket/command/c46/CCMD46B.cpp \
	Game/socket/command/c46/CCMD463.cpp \
	Game/socket/command/c46/CCMD468.cpp \
	Game/socket/command/c46/CCMD46C.cpp \
	Game/socket/command/s10/SCMD108.cpp \
	Game/socket/command/s10/SCMD105.cpp \
	Game/socket/command/s10/SCMD107.cpp \
	Game/socket/command/s10/SCMD102.cpp \
	Game/socket/command/s10/SCMD109.cpp \
	Game/socket/command/s15/SCMD15A.cpp \
	Game/socket/command/s15/SCMD157.cpp \
	Game/socket/command/s15/SCMD15E.cpp \
	Game/socket/command/s15/SCMD153.cpp \
	Game/socket/command/s15/SCMD15C.cpp \
	Game/socket/command/s15/SCMD158.cpp \
	Game/socket/command/s15/SCMD150.cpp \
	Game/socket/command/s15/SCMD151.cpp \
	Game/socket/command/s15/SCMD155.cpp \
	Game/socket/command/s13/SCMD139.cpp \
	Game/socket/command/s13/SCMD135.cpp \
	Game/socket/command/s13/SCMD13D.cpp \
	Game/socket/command/s13/SCMD132.cpp \
	Game/socket/command/s13/SCMD131.cpp \
	Game/socket/command/s13/SCMD13C.cpp \
	Game/socket/command/s13/SCMD137.cpp \
	Game/socket/command/s13/SCMD133.cpp \
	Game/socket/command/s1d/SCMD1D6.cpp \
	Game/socket/command/s1d/SCMD1DD.cpp \
	Game/socket/command/s1d/SCMD1DB.cpp \
	Game/socket/command/s1d/SCMD1DF.cpp \
	Game/socket/command/s3d/SCMD3DF.cpp \
	Game/socket/command/s3d/SCMD3DB.cpp \
	Game/socket/command/c32/CCMD32C.cpp \
	Game/socket/command/s44/SCMD44B.cpp \
	Game/socket/command/s44/SCMD447.cpp \
	Game/socket/command/s44/SCMD446.cpp \
	Game/socket/command/s44/SCMD444.cpp \
	Game/socket/command/s44/SCMD443.cpp \
	Game/socket/command/s44/SCMD442.cpp \
	Game/socket/command/s44/SCMD440.cpp \
	Game/socket/command/s44/SCMD44C.cpp \
	Game/socket/command/s44/SCMD44A.cpp \
	Game/socket/command/c25/CCMD25B.cpp \
	Game/socket/command/c25/CCMD25D.cpp \
	Game/socket/command/s1a/SCMD1A5.cpp \
	Game/socket/command/s1a/SCMD1A3.cpp \
	Game/socket/command/s1a/SCMD1A7.cpp \
	Game/socket/command/s1a/SCMD1AB.cpp \
	Game/socket/command/s1a/SCMD1A9.cpp \
	Game/socket/command/s1a/SCMD1AE.cpp \
	Game/socket/command/s1a/SCMD1A1.cpp \
	Game/socket/command/s1e/SCMD1E6.cpp \
	Game/socket/command/s1e/SCMD1EE.cpp \
	Game/socket/command/s1e/SCMD1E3.cpp \
	Game/socket/command/s1e/SCMD1ED.cpp \
	Game/socket/command/s1e/SCMD1E1.cpp \
	Game/socket/command/s1e/SCMD1EF.cpp \
	Game/socket/command/s38/SCMD38F.cpp \
	Game/socket/command/s38/SCMD38C.cpp \
	Game/socket/command/c21/CCMD21c.cpp \
	Game/socket/command/c21/CCMD210.cpp \
	Game/socket/command/c21/CCMD21E.cpp \
	Game/socket/command/c21/CCMD21D.cpp \
	Game/socket/command/c21/CCMD217.cpp \
	Game/socket/command/c21/CCMD212.cpp \
	Game/socket/command/s17/SCMD172.cpp \
	Game/socket/command/s17/SCMD17D.cpp \
	Game/socket/command/s17/SCMD17F.cpp \
	Game/socket/command/s45/SCMD45F.cpp \
	Game/socket/command/s45/SCMD455.cpp \
	Game/socket/command/s45/SCMD453.cpp \
	Game/socket/command/s45/SCMD45B.cpp \
	Game/socket/command/s45/SCMD459.cpp \
	Game/socket/command/s45/SCMD451.cpp \
	Game/socket/command/s45/SCMD45A.cpp \
	Game/socket/command/s41/SCMD411.cpp \
	Game/socket/command/s41/SCMD41A.cpp \
	Game/socket/command/s41/SCMD414.cpp \
	Game/socket/command/s41/SCMD418.cpp \
	Game/socket/command/s41/SCMD419.cpp \
	Game/socket/command/s29/SCMD295.cpp \
	Game/socket/command/s29/SCMD291.cpp \
	Game/socket/command/s29/SCMD29E.cpp \
	Game/socket/command/s29/SCMD29A.cpp \
	Game/socket/command/c35/CCMD353.cpp \
	Game/socket/command/c35/CCMD359.cpp \
	Game/socket/command/c35/CCMD357.cpp \
	Game/socket/command/c35/CCMD355.cpp \
	Game/socket/command/c35/CCMD35B.cpp \
	Game/socket/command/c35/CCMD351.cpp \
	Game/socket/command/s20/SCMD207.cpp \
	Game/socket/command/s20/SCMD205.cpp \
	Game/socket/command/s20/SCMD201.cpp \
	Game/socket/command/s20/SCMD209.cpp \
	Game/socket/command/s20/SCMD20d.cpp \
	Game/socket/command/s20/SCMD20b.cpp \
	Game/socket/command/s20/SCMD20F.cpp \
	Game/socket/command/c18/CCMD184.cpp \
	Game/socket/command/c18/CCMD182.cpp \
	Game/socket/command/c18/CCMD189.cpp \
	Game/socket/command/c18/CCMD180.cpp \
	Game/socket/command/s0f/SCMD0F1.cpp \
	Game/socket/command/s0f/SCMD0F2.cpp \
	Game/socket/command/c1a/CCMD1A4.cpp \
	Game/socket/command/c1a/CCMD1AA.cpp \
	Game/socket/command/c1a/CCMD1A6.cpp \
	Game/socket/command/c1a/CCMD1A8.cpp \
	Game/socket/command/c1a/CCMD1A0.cpp \
	Game/socket/command/c1a/CCMD1A2.cpp \
	Game/socket/command/c16/CCMD16A.cpp \
	Game/socket/command/c16/CCMD16B.cpp \
	Game/socket/command/c16/CCMD16E.cpp \
	Game/socket/command/c16/CCMD166.cpp \
	Game/socket/command/c16/CCMD169.cpp \
	Game/socket/command/c16/CCMD160.cpp \
	Game/socket/command/c16/CCMD164.cpp \
	Game/socket/command/c16/CCMD168.cpp \
	Game/socket/command/c16/CCMD162.cpp \
	Game/socket/command/c20/CCMD200.cpp \
	Game/socket/command/c20/CCMD208.cpp \
	Game/socket/command/c20/CCMD20E.cpp \
	Game/socket/command/c20/CCMD20A.cpp \
	Game/socket/command/c20/CCMD204.cpp \
	Game/socket/command/c20/CCMD206.cpp \
	Game/socket/command/c20/CCMD20c.cpp \
	Game/socket/command/s18/SCMD18F.cpp \
	Game/socket/command/s18/SCMD18A.cpp \
	Game/socket/command/s18/SCMD186.cpp \
	Game/socket/command/s18/SCMD183.cpp \
	Game/socket/command/s18/SCMD18D.cpp \
	Game/socket/command/s18/SCMD188.cpp \
	Game/socket/command/s18/SCMD187.cpp \
	Game/socket/command/s18/SCMD18E.cpp \
	Game/socket/command/s18/SCMD181.cpp \
	Game/socket/command/s18/SCMD18B.cpp \
	Game/socket/command/s18/SCMD185.cpp \
	Game/socket/command/s18/SCMD18C.cpp \
	Game/socket/command/c41/CCMD410.cpp \
	Game/socket/command/c41/CCMD413.cpp \
	Game/socket/command/s3b/SCMD3B7.cpp \
	Game/socket/command/s3b/SCMD3B1.cpp \
	Game/socket/command/s3b/SCMD3B3.cpp \
	Game/socket/command/s3b/SCMD3B5.cpp \
	Game/socket/command/s31/SCMD31F.cpp \
	Game/socket/command/s31/SCMD318.cpp \
	Game/socket/command/s31/SCMD31A.cpp \
	Game/socket/command/s31/SCMD310.cpp \
	Game/socket/command/s31/SCMD316.cpp \
	Game/socket/command/s31/SCMD314.cpp \
	Game/socket/command/s31/SCMD31D.cpp \
	Game/socket/command/s31/SCMD31B.cpp \
	Game/socket/command/s31/SCMD319.cpp \
	Game/socket/command/s31/SCMD312.cpp \
	Game/socket/command/s1c/SCMD1CD.cpp \
	Game/socket/command/s1c/SCMD1C7.cpp \
	Game/socket/command/s1c/SCMD1C1.cpp \
	Game/socket/command/s1c/SCMD1C3.cpp \
	Game/socket/command/s1c/SCMD1C6.cpp \
	Game/socket/command/s1c/SCMD1CB.cpp \
	Game/socket/command/s21/SCMD213.cpp \
	Game/socket/command/s21/SCMD216.cpp \
	Game/socket/command/s21/SCMD21F.cpp \
	Game/socket/command/s21/SCMD211.cpp \
	Game/socket/command/s21/SCMD219.cpp \
	Game/socket/command/s21/SCMD214.cpp \
	Game/socket/command/c1d/CCMD1D9.cpp \
	Game/socket/command/s3c/SCMD3CF.cpp \
	Game/socket/command/s3c/SCMD3C8.cpp \
	Game/socket/command/s3c/SCMD3CB.cpp \
	Game/socket/command/s3c/SCMD3C9.cpp \
	Game/socket/command/s16/SCMD161.cpp \
	Game/socket/command/s16/SCMD16D.cpp \
	Game/socket/command/s16/SCMD163.cpp \
	Game/socket/command/s16/SCMD16F.cpp \
	Game/socket/command/s16/SCMD167.cpp \
	Game/socket/command/s16/SCMD165.cpp \
	Game/socket/command/c17/CCMD17E.cpp \
	Game/socket/command/c17/CCMD170.cpp \
	Game/socket/command/c17/CCMD171.cpp \
	Game/socket/command/c17/CCMD17A.cpp \
	Game/socket/command/c17/CCMD178.cpp \
	Game/socket/command/c17/CCMD176.cpp \
	Game/socket/command/c2e/CCMD2EA.cpp \
	Game/socket/command/c2e/CCMD2E7.cpp \
	Game/socket/command/c2e/CCMD2EC.cpp \
	Game/socket/command/c2e/CCMD2E0.cpp \
	Game/socket/command/c2e/CCMD2EE.cpp \
	Game/socket/command/c2e/CCMD2E5.cpp \
	Game/socket/command/c2e/CCMD2E2.cpp \
	Game/socket/command/c2e/CCMD2E4.cpp \
	Game/socket/command/s46/SCMD464.cpp \
	Game/socket/command/s46/SCMD460.cpp \
	Game/socket/command/s46/SCMD46D.cpp \
	Game/socket/command/s46/SCMD46A.cpp \
	Game/socket/command/s46/SCMD46F.cpp \
	Game/socket/command/s46/SCMD46E.cpp \
	Game/socket/command/s46/SCMD462.cpp \
	Game/socket/command/s46/SCMD465.cpp \
	Game/socket/command/s34/SCMD349.cpp \
	Game/socket/command/s24/SCMD24B.cpp \
	Game/socket/command/s24/SCMD24F.cpp \
	Game/socket/command/s2c/SCMD2CC.cpp \
	Game/socket/command/s2c/SCMD2C4.cpp \
	Game/socket/command/s2c/SCMD2C9.cpp \
	Game/socket/command/s2c/SCMD2CE.cpp \
	Game/socket/command/s2c/SCMD2C7.cpp \
	Game/socket/command/s2c/SCMD2C5.cpp \
	Game/socket/command/s2c/SCMD2C3.cpp \
	Game/socket/command/s2c/SCMD2C8.cpp \
	Game/socket/command/s28/SCMD281.cpp \
	Game/socket/command/s28/SCMD28B.cpp \
	Game/socket/command/s28/SCMD287.cpp \
	Game/socket/command/s28/SCMD285.cpp \
	Game/socket/command/s28/SCMD28F.cpp \
	Game/socket/command/s2d/SCMD2D3.cpp \
	Game/socket/command/s2d/SCMD2D5.cpp \
	Game/socket/command/s2d/SCMD2D7.cpp \
	Game/socket/command/s2d/SCMD2DF.cpp \
	Game/socket/command/c19/CCMD19E.cpp \
	Game/socket/command/c19/CCMD196.cpp \
	Game/socket/command/c19/CCMD190.cpp \
	Game/socket/command/c19/CCMD192.cpp \
	Game/socket/command/c19/CCMD19C.cpp \
	Game/socket/command/s11/SCMD11A.cpp \
	Game/socket/command/s11/SCMD112.cpp \
	Game/socket/command/s11/SCMD111.cpp \
	Game/socket/command/s11/SCMD113.cpp \
	Game/socket/command/s11/SCMD11F.cpp \
	Game/socket/command/s11/SCMD11D.cpp \
	Game/socket/command/s11/SCMD11B.cpp \
	Game/socket/command/s11/SCMD118.cpp \
	Game/socket/command/s11/SCMD11C.cpp \
	Game/socket/command/s36/SCMD363.cpp \
	Game/socket/command/s36/SCMD369.cpp \
	Game/socket/command/s36/SCMD366.cpp \
	Game/socket/command/s36/SCMD36E.cpp \
	Game/socket/command/s36/SCMD36C.cpp \
	Game/socket/command/s36/SCMD361.cpp \
	Game/socket/command/s36/SCMD367.cpp \
	Game/socket/command/c01/CCMD010.cpp \
	Game/socket/command/c01/CCMD011.cpp \
	Game/socket/command/s39/SCMD39B.cpp \
	Game/socket/command/s39/SCMD39A.cpp \
	Game/socket/command/s39/SCMD39C.cpp \
	Game/socket/command/s39/SCMD39D.cpp \
	Game/socket/command/c15/CCMD15D.cpp \
	Game/socket/command/c15/CCMD159.cpp \
	Game/socket/command/c15/CCMD154.cpp \
	Game/socket/command/c15/CCMD15F.cpp \
	Game/socket/command/c15/CCMD15B.cpp \
	Game/socket/command/c15/CCMD156.cpp \
	Game/socket/command/c37/CCMD374.cpp \
	Game/socket/command/c37/CCMD37D.cpp \
	Game/socket/command/c37/CCMD372.cpp \
	Game/socket/command/c13/CCMD136.cpp \
	Game/socket/command/c13/CCMD13B.cpp \
	Game/socket/command/c13/CCMD138.cpp \
	Game/socket/command/c13/CCMD134.cpp \
	Game/socket/command/c10/CCMD104.cpp \
	Game/socket/command/c10/CCMD101.cpp \
	Game/socket/command/c10/CCMD10F.cpp \
	Game/socket/command/c10/CCMD106.cpp \
	Game/socket/command/s30/SCMD303.cpp \
	Game/socket/command/s30/SCMD30C.cpp \
	Game/socket/command/s30/SCMD300.cpp \
	Game/socket/command/s30/SCMD30A.cpp \
	Game/socket/command/s30/SCMD309.cpp \
	Game/socket/command/s30/SCMD305.cpp \
	Game/socket/command/s30/SCMD301.cpp \
	Game/socket/command/s30/SCMD30E.cpp \
	Game/socket/command/s37/SCMD37C.cpp \
	Game/socket/command/s37/SCMD373.cpp \
	Game/socket/command/s37/SCMD376.cpp \
	Game/socket/command/s37/SCMD375.cpp \
	Game/socket/command/s27/SCMD275.cpp \
	Game/socket/command/s27/SCMD273.cpp \
	Game/socket/command/s27/SCMD27B.cpp \
	Game/socket/command/s27/SCMD271.cpp \
	Game/socket/command/s27/SCMD27D.cpp \
	Game/socket/command/s27/SCMD277.cpp \
	Game/socket/command/s27/SCMD27F.cpp \
	Game/socket/command/s27/SCMD279.cpp \
	Game/socket/command/s27/SCMD27E.cpp \
	Game/socket/command/s12/SCMD124.cpp \
	Game/socket/command/s12/SCMD120.cpp \
	Game/socket/command/s12/SCMD123.cpp \
	Game/socket/command/s12/SCMD12D.cpp \
	Game/socket/command/s12/SCMD12F.cpp \
	Game/socket/command/c28/CCMD284.cpp \
	Game/socket/command/c28/CCMD286.cpp \
	Game/socket/command/c29/CCMD292.cpp \
	Game/socket/command/c29/CCMD294.cpp \
	Game/socket/command/c36/CCMD368.cpp \
	Game/socket/command/c36/CCMD36F.cpp \
	Game/socket/command/c36/CCMD364.cpp \
	Game/socket/command/c36/CCMD360.cpp \
	Game/socket/command/c36/CCMD362.cpp \
	Game/socket/command/c24/CCMD24A.cpp \
	Game/socket/command/s32/SCMD3C2.cpp \
	Game/socket/command/s32/SCMD324.cpp \
	Game/socket/command/s32/SCMD321.cpp \
	Game/socket/command/s32/SCMD323.cpp \
	Game/socket/command/s19/SCMD19A.cpp \
	Game/socket/command/s19/SCMD197.cpp \
	Game/socket/command/s19/SCMD19F.cpp \
	Game/socket/command/s19/SCMD191.cpp \
	Game/socket/command/s19/SCMD199.cpp \
	Game/socket/command/s19/SCMD19D.cpp \
	Game/socket/command/s19/SCMD19C.cpp \
	Game/socket/command/s19/SCMD19B.cpp \
	Game/socket/command/s19/SCMD193.cpp \
	Game/socket/command/s3a/SCMD3AA.cpp \
	Game/socket/command/s3a/SCMD3AE.cpp \
	Game/socket/command/s3a/SCMD3AC.cpp \
	Game/socket/command/s35/SCMD358.cpp \
	Game/socket/command/s35/SCMD35C.cpp \
	Game/socket/command/s35/SCMD35D.cpp \
	Game/socket/command/s35/SCMD352.cpp \
	Game/socket/command/s35/SCMD35A.cpp \
	Game/socket/command/s35/SCMD35F.cpp \
	Game/socket/command/s35/SCMD354.cpp \
	Game/socket/command/s35/SCMD35E.cpp \
	Game/socket/command/s35/SCMD350.cpp \
	Game/socket/command/s14/SCMD140.cpp \
	Game/socket/command/s14/SCMD144.cpp \
	Game/socket/command/s14/SCMD142.cpp \
	Game/socket/command/c2a/CCMD2A4.cpp \
	Game/socket/command/c12/CCMD122.cpp \
	Game/socket/command/c12/CCMD121.cpp \
	Game/socket/command/c12/CCMD128.cpp \
	Game/socket/command/s25/SCMD25E.cpp \
	Game/socket/command/s25/SCMD25C.cpp \
	Game/socket/command/s2e/SCMD2E9.cpp \
	Game/socket/command/s2e/SCMD2EF.cpp \
	Game/socket/command/s2e/SCMD2ED.cpp \
	Game/socket/command/s2e/SCMD2E3.cpp \
	Game/socket/command/s2e/SCMD2EB.cpp \
	Game/socket/command/s2e/SCMD2E8.cpp \
	Game/socket/command/s2e/SCMD2E6.cpp \
	Game/socket/command/s2e/SCMD2E1.cpp \
	Game/socket/command/s42/SCMD42B.cpp \
	Game/socket/command/s42/SCMD423.cpp \
	Game/socket/command/s42/SCMD427.cpp \
	Game/socket/command/s42/SCMD425.cpp \
	Game/socket/command/s42/SCMD421.cpp \
	Game/socket/command/s42/SCMD429.cpp \
	Game/socket/command/s2b/SCMD2B9.cpp \
	Game/socket/command/s2b/SCMD2B2.cpp \
	Game/socket/command/s2b/SCMD2BB.cpp \
	Game/socket/command/s2b/SCMD2B4.cpp \
	Game/socket/command/s2b/SCMD2B6.cpp \
	Game/socket/command/s2b/SCMD2B3.cpp \
	Game/socket/command/s2b/SCMD2B7.cpp \
	Game/socket/command/s2b/SCMD2B1.cpp \
	Game/socket/command/s2b/SCMD2BF.cpp \
	Game/socket/command/c1e/CCMD1E7.cpp \
	Game/socket/command/c1e/CCMD1E8.cpp \
	Game/socket/command/c1e/CCMD1E5.cpp \
	Game/socket/command/c1e/CCMD1E4.cpp \
	Game/socket/command/c1e/CCMD1E2.cpp \
	Game/socket/command/s40/SCMD405.cpp \
	Game/socket/command/s40/SCMD40D.cpp \
	Game/socket/command/s40/SCMD40B.cpp \
	Game/socket/command/s40/SCMD409.cpp \
	Game/socket/command/s40/SCMD407.cpp \
	Game/socket/command/s40/SCMD401.cpp \
	Game/socket/command/s40/SCMD403.cpp \
	Game/socket/command/s2f/SCMD2FF.cpp \
	Game/socket/command/s2a/SCMD2A5.cpp \
	Game/socket/command/s2a/SCMD2A1.cpp \
	Game/socket/command/s2a/SCMD2A7.cpp \
	Game/socket/command/s2a/SCMD2A3.cpp \
	Game/socket/command/s43/SCMD433.cpp \
	Game/socket/command/s43/SCMD435.cpp \
	Game/socket/command/s43/SCMD431.cpp \
	Game/socket/command/c30/CCMD308.cpp \
	Game/socket/command/c30/CCMD306.cpp \
	Game/socket/command/c30/CCMD304.cpp \
	Game/socket/command/c30/CCMD307.cpp \
	Game/socket/command/c30/CCMD30B.cpp \
	Game/socket/command/c30/CCMD302.cpp \
	Game/socket/command/c30/CCMD30F.cpp \
	Game/socket/command/c30/CCMD30D.cpp \
	Game/socket/command/c31/CCMD317.cpp \
	Game/socket/command/c31/CCMD315.cpp \
	Game/socket/command/c31/CCMD313.cpp \
	Game/socket/command/c31/CCMD31C.cpp \
	Game/socket/command/c31/CCMD31E.cpp \
	Game/socket/command/c31/CCMD311.cpp \
	Game/socket/command/s1b/SCMD1B7.cpp \
	Game/socket/command/s1b/SCMD1B2.cpp \
	Game/socket/command/s1b/SCMD1BC.cpp \
	Game/socket/command/s1b/SCMD1BF.cpp \
	Game/socket/command/s1b/SCMD1B8.cpp \
	Game/socket/command/c11/CCMD116.cpp \
	Game/socket/command/c11/CCMD110.cpp \
	Game/socket/command/c11/CCMD11E.cpp \
	Game/socket/command/c11/CCMD114.cpp \
	Game/socket/command/c11/CCMD115.cpp \
	Game/socket/command/c11/CCMD119.cpp \
	Game/socket/command/c44/CCMD445.cpp \
	Game/socket/command/c44/CCMD449.cpp \
	Game/socket/command/c44/CCMD448.cpp \
	Game/socket/command/c44/CCMD441.cpp \
	Game/events/GameDispatcher.cpp \
	Game/mvc/Proxy.cpp \
	Game/mvc/Mediator.cpp \
	Game/mvc/Facade.cpp \
	Game/mvc/SimpleCommand.cpp \
	Game/control/tower/TowerCommand.cpp \
	Game/control/task/TaskProxyCommand.cpp \
	Game/control/appoint/AppointCommand.cpp \
	Game/control/bank/BankProxyCommand.cpp \
	Game/control/figure/FigureCommand.cpp \
	Game/control/ModelCommand.cpp \
	Game/control/wordBoss/WorldBossCmd.cpp \
	Game/control/arena/ArenaProxyCommand.cpp \
	Game/control/formation/FormationCommand.cpp \
	Game/control/vip/VipCommand.cpp \
	Game/control/battle/SceneFightProxyCommand.cpp \
	Game/control/recruit/RecruitCommand.cpp \
	Game/control/ControlCommand.cpp \
	Game/control/train/TrainCommand.cpp \
	Game/control/onlineReward/OnlineRewardCommand.cpp \
	Game/control/ViewCommand.cpp \
	Game/control/guild/GuildChangeCommand.cpp \
	Game/control/skill/SkillCommand.cpp \
	Game/control/backpack/BagProxyCommand.cpp \
	Game/control/trader/TraderProxyCommand.cpp \
	Game/control/campFight/CampFightCommand.cpp \
	Game/control/friend/FriendProxyCommand.cpp \
	Game/control/scene/SceneCommand.cpp \
	Game/control/scene/SceneStoryProxyCommand.cpp \
	Game/control/scene/enhance/EnhanceStoryCommand.cpp \
	Game/control/scene/enhance/TriggerStoryCommand.cpp \
	Game/control/scene/SceneProxyCommand.cpp \
	Game/control/mail/MailProxyCommand.cpp \
	Game/control/crystal/CrystalCommand.cpp \
	Game/control/ranking/RankingCommand.cpp \
	Game/control/com/ComProxyCommand.cpp \
	Game/control/egg/EggCommand.cpp \
	main/BaseType.cpp \
	main/LoginManage.cpp \
	main/AppDelegate.cpp \
	UIComponent/UIClipBaseView.cpp \
	UIComponent/Confirm.cpp \
	UIComponent/CCStrokeLabel/CCStrokeLabel.cpp \
	UIComponent/CustomCD.cpp \
	UIComponent/TextFieldTTFEx.cpp \
	UIComponent/UIListView/CCUIListView.cpp \
	UIComponent/PopContainer.cpp \
	UIComponent/Message.cpp \
	UIComponent/MessageItem.cpp \
	UIComponent/CustomButton.cpp \
	UIComponent/CCUIBaseClipLayer.cpp \
	UIComponent/SpriteNode.cpp \
	UIComponent/LHLabelTTF.cpp \
	UIComponent/LHMenuItemLabel.cpp \
	UIComponent/ImageContain.cpp \
	UIComponent/TextFieldTTF.cpp \
	UIComponent/NewEAlert.cpp \
	UIComponent/UITaskPanelListView/CCUITaskPanelItem.cpp \
	UIComponent/UITaskPanelListView/CCUITaskPanelListView.cpp \
	UIComponent/FocusNode.cpp \
	UIComponent/UIPrintView/CCUIPrintView.cpp \
	UIComponent/UIPrintView/CCUIPrintLine.cpp \
	UIComponent/Alert.cpp \
	UIComponent/CCUIPartialScrollView.cpp \
	UIComponent/KKLabelTTF.cpp \
	UIComponent/KKUIListView/KKCCUIListView.cpp \
	UIComponent/UIBaseView.cpp \
	UIComponent/TextInputConfirm.cpp \
	UIComponent/LayerNode.cpp \
	UIComponent/MailTextFieldTTF.cpp \
	UIComponent/CCUIBackground.cpp \
	UIComponent/UICheckButton/UICheckButton.cpp \
	UIComponent/PopUIBg.cpp \
	UIComponent/MessageInfoBox.cpp \
	UIComponent/SpriteBtn.cpp \
	com/bear/manager/DisplayObjectManager.cpp \
	com/bear/utils/StageProxy.cpp \
	com/utils/sort/SortUtil.cpp \
	com/utils/flash/TweenLite.cpp \
	com/utils/flash/CCIEventDispatcher.cpp \
	com/utils/findPath/FindPath8.cpp \
	com/utils/findPath/Diagonal.cpp \
	com/utils/updateRes/ResUpdateInfo.cpp \
	com/utils/updateRes/CheckRes.cpp \
	com/utils/updateRes/Md5Info.cpp \
	com/utils/updateRes/ResourceModel.cpp \
	com/utils/updateRes/MetaConfigure.cpp \
	com/utils/thread/BaseThread.cpp \
	com/utils/thread/MessageMgr.cpp \
	com/utils/loader/LoaderItem.cpp \
	com/utils/loader/KKAnimationFactory.cpp \
	com/utils/loader/GameLoaderManage.cpp \
	com/utils/loader/AnimationManager.cpp \
	com/utils/xml/tinyxml.cpp \
	com/utils/xml/tinyxmlerror.cpp \
	com/utils/xml/tinyxmlparser.cpp \
	com/utils/xml/TinyElementHandler.cpp \
	com/utils/xml/tinystr.cpp \
	com/utils/http/http_base64.c \
	com/utils/http/ghttp.c \
	com/utils/http/http_resp.c \
	com/utils/http/http_uri.c \
	com/utils/http/http_req.c \
	com/utils/http/http_date.c \
	com/utils/http/http_hdrs.c \
	com/utils/http/http_trans.c \


LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/Game \
	$(LOCAL_PATH)/Game/control \
	$(LOCAL_PATH)/com \
	$(LOCAL_PATH)/UIComponent \
	$(LOCAL_PATH)/main \
	$(LOCAL_PATH)/../ios \
	$(LOCAL_PATH)/../android \
	$(LOCAL_PATH)/../../../cocos2dx/include \

LOCAL_EXPORT_C_INCLUDES := \
	$(LOCAL_PATH)/Game \
	$(LOCAL_PATH)/com \
	$(LOCAL_PATH)/UIComponent \
	$(LOCAL_PATH)/main \
	$(LOCAL_PATH)/../ios \
	$(LOCAL_PATH)/../android \
	$(LOCAL_PATH)/../../../cocos2dx/include \

LOCAL_CFLAGS += -g
LOCAL_CFLAGS += -ggdb
LOCAL_CFLAGS += -O1

LOCAL_STATIC_LIBRARIES := png_static_prebuilt
LOCAL_STATIC_LIBRARIES += xml2_static_prebuilt
LOCAL_STATIC_LIBRARIES += jpeg_static_prebuilt
LOCAL_WHOLE_STATIC_LIBRARIES += cocos2dx_static
                
LOCAL_SHARED_LIBRARIES := cocosdenshion_shared
            
include $(BUILD_STATIC_LIBRARY)

$(call import-module,cocos2dx/platform/third_party/android/modules/libpng)
$(call import-module,cocos2dx/platform/third_party/android/modules/libxml2)
$(call import-module,cocos2dx/platform/third_party/android/modules/libjpeg)
